In [1]:
import numpy as np
import tkinter


In [8]:
def parsemap(filename: str):
    """Obtiene un np.ndarray para representar el mapa de energías desde el
    archivo filename"""
    with open(filename) as f:
        input = f.readlines()
    energymap = []
    for s in input: 
        row = []
        for c in s: 
            if c != "\n": row.append(int(c))
        energymap.append(row)
    return np.array(energymap)

In [10]:
sudoku = parsemap('sudoku.txt')

[[0 0 2 0 0 1 0 3 9]
 [0 0 0 0 0 0 0 0 0]
 [0 0 6 8 3 2 7 0 0]
 [0 0 9 2 7 0 0 8 0]
 [2 8 0 0 9 3 0 6 0]
 [7 0 0 0 0 8 5 0 0]
 [0 0 0 7 0 4 6 0 0]
 [0 0 0 0 5 0 9 4 0]
 [0 6 4 3 0 0 0 0 5]]


In [46]:
#crear una ventana
ventana = tkinter.Tk()
ventana.geometry("500x500")

def saludo(nombre):
    print("Hola "+nombre)

etiqueta = tkinter.Label(ventana, text = "Hola mundo", bg="grey") #crea una etiqueta
etiqueta.pack(fill=tkinter.X, expand = 1) #método más simple para mostrar

#boton1 = tkinter.Button(ventana,text="Presiona", command = lambda: saludo("Python"))
#boton1 = tkinter.Button(ventana,text="Click", command = lambda: print("Hola mundo"))

cajaTexto = tkinter.Entry(ventana, font="Helvetica 30")
cajaTexto.pack()

boton1 = tkinter.Button(ventana,text="Click", command = lambda: textoDeLaCaja())
boton1.pack()

def textoDeLaCaja():
    input=cajaTexto.get()
    #print(input)
    etiqueta["text"]=input

etiqueta =tkinter.Label(ventana)
etiqueta.pack()

ventana.mainloop() #lleva el registro de todo lo que sucede en la ventana

In [1]:
len([3])

1

In [2]:
len([])

0

In [4]:
[]==True

False

In [8]:
[1,2,3]!=[] 

True

In [10]:
[1,2,3].size()>0

AttributeError: 'list' object has no attribute 'size'