In [12]:
from flask import Flask
from flask import request
from flask import render_template
import numpy as np
import sudoku as sud

app = Flask(__name__)


@app.route('/')
def index():
    return render_template("index.html", nombre = name, edad = age, sudoku = solucion)

 
#funciona con esta URL: http://127.0.0.1:5000/params?params1=Juan_Manuel&params2=Jimenez_Cruz
#?params=1
#@app.route('/params')
#def saluda():
#    param1 = request.args.get("params1","no contiene este parametro")
#    param2 = request.args.get("params2","no contiene este parametro")
#    return f"El parametro es {param1} {param2}"


if __name__ == '__main__':
    name = "Juan Manuel"
    age = 25

    sudoku   = sud.parsemap("sudoku3.txt")
    solucion = sud.resolver("sudoku3.txt")
    app.run(debug=True)

[[1 6 2 3 8 7 4 9 5]
 [9 3 7 5 4 6 8 2 1]
 [8 5 4 9 2 1 3 6 7]
 [6 7 9 8 5 4 1 3 2]
 [4 8 1 2 7 3 6 5 9]
 [3 2 5 1 6 9 7 4 8]
 [5 4 8 7 3 2 9 1 6]
 [7 1 6 4 9 5 2 8 3]
 [2 9 3 6 1 8 5 7 4]]


127.0.0.1 - - [20/Jan/2022 00:20:42] "GET / HTTP/1.1" 200 -


 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [20/Jan/2022 00:20:47] "GET / HTTP/1.1" 200 -
