In [7]:
from flask import Flask
from flask import request
from flask import render_template
import numpy as np
import sudoku as sud

app = Flask(__name__)


@app.route('/')
def index():
    return render_template("index.html", nombre = name, edad = age, sudoku = solucion)

 
#funciona con esta URL: http://127.0.0.1:5000/params?params1=Juan_Manuel&params2=Jimenez_Cruz
#?params=1
#@app.route('/params')
#def saluda():
#    param1 = request.args.get("params1","no contiene este parametro")
#    param2 = request.args.get("params2","no contiene este parametro")
#    return f"El parametro es {param1} {param2}"


if __name__ == '__main__':
    name = "Juan Manuel"
    age = 25

    sudoku   = sud.parsemap("sudoku3.txt")
    solucion = sud.sol(sudoku)
    app.run()#debug = True, port = 8000)

[[8 7 2 5 6 1 4 3 9]
 [5 3 1 9 4 7 8 2 6]
 [4 9 6 8 3 2 7 5 1]
 [6 1 9 2 7 5 3 8 4]
 [2 8 5 4 9 3 1 6 7]
 [7 4 3 6 1 8 5 9 2]
 [9 5 8 7 2 4 6 1 3]
 [3 2 7 1 5 6 9 4 8]
 [1 6 4 3 8 9 2 7 5]]
 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [18/Jan/2022 23:48:03] "GET / HTTP/1.1" 200 -
