In [72]:
import numpy as np
def parsemap(filename: str):
    """Obtiene un np.ndarray para representar el mapa de energías desde el
    archivo filename"""
    with open(filename) as f:
        input = f.readlines()
    energymap = []
    for s in input: 
        row = []
        for c in s: 
            if c != "\n": row.append(int(c))
        energymap.append(row)
    return np.array(energymap)
    
a = parsemap("sodoku2.txt")
m, n = a.shape


In [62]:
#dividir por secciones los cuadros
#def cuadro (fila, columna, numero, a):
    #0 para la primera seccion, 3 para la segunda seccion, 6 para la tercera seccion
#    x = (fila // 3)*3
#    y = (columna // 3)*3

    #haciendo la verificacion
#    for i in range (0,3):
#        for j in range(0,3):
            #x y y, es la posicion inicial (sumando i chequea los otros 2):
#            if a[x+i][y+j] == numero:
#                return False
#            else:
#                return True

In [73]:
def posibilidad (fila, columna, numero, a):
     #Chequeando si el numero aparece en la fila
    for i in range (0,9):
        if a[fila][i] == numero:
            return False

    #chequeando si el numero aparece en la columna
    for i in range (0,9):
        if a[i][columna] == numero:
            return False

    #chequear si esta en el cuadro de 3x3
    x = (fila // 3) * 3
    y = (columna // 3) * 3

    #haciendo la verificacion
    for i in range (0,3):
        for j in range(0,3):
            #x y y, es la posicion inicial (sumando i chequea los otros 2):
            if a[x+i][y+j] == numero:
                return False
    return True
            

In [70]:
#posibilidad(1,1,8,parsemap("sodoku1.txt"))

False

In [74]:
# solucion 2
def sol(sodoku):
    for x in range(m):
        for y in range(n):
            if sodoku[x][y] == 0:
                for valor in range (1,10):
                    if posibilidad(x, y, valor, sodoku):
                        sodoku[x][y] = valor
                        sol(sodoku)
                        sodoku[x][y] = 0
                return
    print(sodoku)
    return

sol(a)
    

[[9 6 3 1 7 4 2 5 8]
 [1 7 8 3 2 5 6 4 9]
 [2 5 4 6 8 9 7 3 1]
 [8 2 1 4 3 7 5 9 6]
 [4 9 6 8 5 2 3 1 7]
 [7 3 5 9 6 1 8 2 4]
 [5 8 9 7 1 3 4 6 2]
 [3 1 7 2 4 6 9 8 5]
 [6 4 2 5 9 8 1 7 3]]
